/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        // Path to chromedriver (Ubuntu installation)
        System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");

        ChromeOptions options = new ChromeOptions();

        // Use Chromium instead of Chrome
        options.setBinary("/usr/bin/chromium-browser");

        // Required for sandbox environments
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");

        WebDriver driver = new ChromeDriver(options);

        try {

            // Open SauceDemo
            driver.get("https://www.saucedemo.com");

            // Enter username
            driver.findElement(By.id("user-name")).sendKeys("standard_user");

            // Enter password
            driver.findElement(By.id("password")).sendKeys("secret_sauce");

            // Click login
            driver.findElement(By.id("login-button")).click();

            System.out.println("Login attempted. Page title: " + driver.getTitle());

        } catch (Exception e) {
            e.printStackTrace();
        }

        // Keep browser open for testing
        // Comment out driver.quit() so browser stays open
        // driver.quit();
    }
}
